-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 14:51:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scholarship
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scholarship` ;

-- -----------------------------------------------------
-- Schema scholarship
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scholarship` DEFAULT CHARACTER SET utf8 ;
USE `scholarship` ;

-- -----------------------------------------------------
-- Table `scholarship`.`Scholarship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Scholarship` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Scholarship` (
  `idScholarship` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idScholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Deanery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Deanery` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Deanery` (
  `idDeanery` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDeanery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Accountant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Accountant` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Accountant` (
  `idAccountant` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `Accountantcol` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccountant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Faculty` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Faculty` (
  `idFaculty` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `studentsNumber` VARCHAR(45) NOT NULL,
  `deanery` INT NOT NULL,
  `accountant` INT NOT NULL,
  PRIMARY KEY (`idFaculty`),
  INDEX `fk_Faculty_Deanery1_idx` (`deanery` ASC) VISIBLE,
  INDEX `fk_Faculty_Accountant1_idx` (`accountant` ASC) VISIBLE,
  CONSTRAINT `fk_Faculty_Deanery1`
    FOREIGN KEY (`deanery`)
    REFERENCES `scholarship`.`Deanery` (`idDeanery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faculty_Accountant1`
    FOREIGN KEY (`accountant`)
    REFERENCES `scholarship`.`Accountant` (`idAccountant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Session` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Session` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `avgMark` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Student` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NOT NULL,
  `recordBook` VARCHAR(45) NOT NULL,
  `bankCard` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Scholarship_idScholarship` INT NOT NULL,
  `faculty` INT NOT NULL,
  `session` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `Scholarship_idScholarship`),
  INDEX `fk_Student_Scholarship_idx` (`Scholarship_idScholarship` ASC) VISIBLE,
  INDEX `fk_Student_Faculty1_idx` (`faculty` ASC) VISIBLE,
  INDEX `fk_Student_Session1_idx` (`session` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Scholarship`
    FOREIGN KEY (`Scholarship_idScholarship`)
    REFERENCES `scholarship`.`Scholarship` (`idScholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Faculty1`
    FOREIGN KEY (`faculty`)
    REFERENCES `scholarship`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Session1`
    FOREIGN KEY (`session`)
    REFERENCES `scholarship`.`Session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scholarship`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scholarship`.`Exam` ;

CREATE TABLE IF NOT EXISTS `scholarship`.`Exam` (
  `idExam` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `mark` VARCHAR(45) NOT NULL,
  `Session` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `fk_Exam_Session1_idx` (`Session` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_Session1`
    FOREIGN KEY (`Session`)
    REFERENCES `scholarship`.`Session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
